# Generated by Django 3.1.4 on 2020-12-30 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_positionids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionids',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.employee'),
        ),
    ]
