# Generated by Django 3.1.4 on 2020-12-30 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.position')),
            ],
        ),
    ]
